# Generated by Django 3.1.2 on 2021-06-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrendatario',
            name='nombreCom',
            field=models.TextField(max_length=50),
        ),
    ]
