# Generated by Django 3.1.2 on 2021-06-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendo', '0002_auto_20210613_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrendatario',
            name='nombreCom',
            field=models.CharField(max_length=20),
        ),
    ]
