# Generated by Django 3.1.2 on 2021-06-13 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arriendo', '0003_auto_20210613_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrendatario',
            old_name='nombreCom',
            new_name='nom',
        ),
    ]
