# Generated by Django 3.1.2 on 2021-06-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arriendo', '0005_arrendador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrendador',
            old_name='imgPerfil',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='arrendatario',
            old_name='imgPerfil',
            new_name='imagen',
        ),
    ]
