# Generated by Django 3.2 on 2021-06-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendo', '0006_auto_20210613_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('n_esta', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('tamaño', models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='Mediano', max_length=8)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='arrendador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='arrendatario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
